### ISSUE TITLE
Action.sh no internet connection bug

### ISSUE THREAD

**Issue by SquadCraftFTW** [daboynb/playcurlNEXT#1]
When I try to run action.sh it says there's no internet connection no matter what I try. Running magisk 27008 on android 14. 

![Screenshot_2024-10-10-04-03-50-798_rgeuqugq.e.r.f.o-edit.jpg](https://github.com/user-attachments/assets/6cf12a82-e829-4053-88af-2d8ef4a75d89)

![Screenshot_2024-10-10-04-05-05-343_rgeuqugq.e.r.f.o-edit.jpg](https://github.com/user-attachments/assets/75e902f0-c8d7-4425-8f38-0dbe851189de)

![Screenshot_2024-10-10-04-06-57-952_rgeuqugq.e.r.f.o-edit.jpg](https://github.com/user-attachments/assets/5887b467-6e55-4792-8136-f911645fd3eb)

**Comment by daboynb** [comment]
HI, I released v1.01 (https://github.com/daboynb/playcurlNEXT/releases/download/v1.01/playcurlNEXT.zip), the bug should be fixed now. 
Thank you.
