### ISSUE TITLE
Questions about the relationship between playcurlNEXT and [PlayIntegrityFix]

### ISSUE THREAD

**Issue by nagae-memooff** [daboynb/playcurlNEXT#2]
I’m sorry if my English isn’t perfect, as I’m not a native speaker. Please bear with me.

I came across a comment on this GitHub page where a user mentioned the following steps:

1. Uninstall the safetynet-fix module and reboot.
2. Next, install this Magisk module: [PlayIntegrityFix](https://github.com/chiteroman/PlayIntegrityFix)
3. Then, install this Magisk module: [PlayIntegrityNEXT](https://github.com/daboynb/PlayIntegrityNEXT)

I followed these steps, and it worked well at first.

However, I noticed that the module in [PlayIntegrityFix](https://github.com/chiteroman/PlayIntegrityFix) has been updated. When I installed the update, I got a message saying "playcurl module removed!" 

When I tried to install the playcurl module, I found that the project had been archived, and I discovered the playcurlNEXT module instead.

I readed the README file, installed and rebooted the playcurlNEXT module, and then rebooted my phone. After that, I saw the playcurl app in my app list.

But now I’m a bit confused, and I have some questions:

1. Should I stop using the old playcurl module and switch to playcurlNEXT?
2. If the answer is yes, should I keep both PlayIntegrityFix and playcurlNEXT modules enabled together?
3. I found the README says “Why a Tasker App and Not service.sh.” Does this mean I need to configure a scheduled task in Tasker to periodically fetch new fingerprints? Is my understanding correct?

**Comment by daboynb** [comment]
Hi,

1. You must remove the old Playcurl to use this!
2. The setup should be PIF + PlaycurlNEXT.
3. The app handles everything automatically. I was simply explaining why I prefer a Tasker app instead of using service.sh.

The issue you described here: 

> "However, I noticed that the module in [PlayIntegrityFix](https://github.com/chiteroman/PlayIntegrityFix) has been updated. When I installed the update, I got a message saying 'playcurl module removed!'" 

is because Chiteroman's module removes mine when someone installs or updates his module. I don't know why.

**Comment by nagae-memooff** [comment]
Thank you for your reply, I understand now. I will try asking to Chiteroman to know what he thinks.
