### ISSUE TITLE
The tasker implementation causes a "phantom alarm" on stock Pixel (Android 14).

### ISSUE THREAD

**Issue by hanakomisa** [daboynb/playcurlNEXT#3]
Once playcurlNEXT is installed, and the root permission is granted from opening the playcurl app, the device will now constantly show an alarm set on the AoD and the QS tile. I confirmed this by factory resetting my phone, and then testing without playcurl installed, no "alarm" is set. Once playcurl is installed however the "phantom alarm" shows up.

For those who wants to keep using playcurlNEXT while getting rid of the "alarm" icon, you can simply uninstall the playcurl app and manually fetch the fingerprint from Magisk actions, as stated in the README.

While this is a small issue, I wanted to bring it to attention as to my knowledge it could also affect Adaptive Charging.

INFO:
Phone: Google Pixel 7
ROM: Stock (Android 14, AP2A.240905.003)
Root: Magisk 28001 (Zygisk and DenyList enabled.)
Modules installed: Play Interity Fix 17.7, playcurlNEXT 1.01

**Comment by daboynb** [comment]
Hi,
Tasker sets alarms to ensure the app is woken by the system and runs every 30 minutes; this is how Tasker works, and I can't change it. 
I'm trying to resolve some issues with service.sh to replace the Tasker app
Here the explanation https://github.com/daboynb/playcurlNEXT?tab=readme-ov-file#why-a-tasker-app-and-not-servicesh
