### ISSUE TITLE
Question about module zip size

### ISSUE THREAD

**Issue by ghost** [daboynb/playcurlNEXT#5]
Hello,

2/3rd of the 30mb module comes from the useless .git folder, you could maybe exclude it in the next releases?

Also, i see that this new project superseds the previous playcurl. How do you feel about the state of development of this new repo? Is it ready yet for a daily drive casual use?

Thanks!

**Comment by daboynb** [comment]
Hi,
Sure, I fixed the current release and  I'll remove the .git folder from all the next releases.

Regarding the other question yes, it's stable, I'm using it without issues daily.
