### ISSUE TITLE
Maybe it doesn't work on my Fold 4.

### ISSUE THREAD

**Issue by Conan179** [daboynb/playcurlNEXT#6]
Hello first of all. It doesn't seem to work on my Samsung Fold 4, I'm writing this on purpose because it could also be that I did something wrong. This is installed:
![2024-10-23 11 30 35](https://github.com/user-attachments/assets/e502610b-0761-4608-837a-2c5e908e3013)
![2024-10-23 11 31 05](https://github.com/user-attachments/assets/d3f27603-5ffd-4a10-ac6c-6aace7f4b621)
and get the message that I did not pass the CTS profile match test.
![2024-10-23 11 25 47](https://github.com/user-attachments/assets/2a4c07da-c7de-4754-88b9-7178889707fb)
Do I need to do anything else now or should it just work now?

**Comment by crok** [comment]
Patience is all you need - Google's ban hammer hit yesterday quite hard and none of the previous fingerprints are working at the very moment, PIF (and the trick behind it) is "_dead_" at the moment.

PS: and forget YA**SN**AC finally.. it is for **S**afety**N**et and [it is practically dead for more than 2 years now](https://developer.android.com/privacy-and-security/safetynet/deprecation-timeline#safetynet_attestation_deprecation_timeline).. You have to check PlayIntegrity with an app like [SPIC](https://play.google.com/store/apps/details?id=com.henrikherzig.playintegritychecker) or [PlayIntegrity API Checker](https://play.google.com/store/apps/details?id=gr.nikolasspyr.integritycheck) or with Play Store itself (Open Play Store -> upper right corner -> profile photo -> Settings -> About -> tap Play Store version 8..10 times until it says developer options are enabled -> go back to Settings -> General -> Developer options -> Integrity check -> this is the very same check all the apps and even Play Services are doing).

**Comment by Conan179** [comment]
Ok no problem.

My problem was that my banking app recognized root and I thought I had done something wrong.

All that messing around changed something and the banking app is working again. It's not a big deal that Google Wallet isn't working at the moment.

Thanks for the info.

Um, OK, I replaced the app, I've had it on there for a while...
![2024-10-23 11 52 15](https://github.com/user-attachments/assets/2cbd9f60-c649-40a5-8977-e3c4c66d9f5f)

**Comment by thevalo** [comment]
Is there any update on this? Did the same, but my device passes only BASIC_INTEGRITY.

**Comment by daboynb** [comment]
Hi,

The fp is valid and working.

Some devices are facing issues passing Device and Strong Integrity with Magisk.

I recommend that you uninstall it and try KSU.

**Comment by daboynb** [comment]
Btw, before that, disable all the modules except for pif and playcurl, reboot and check for integrity.

**Comment by thevalo** [comment]
Alright, my mistake. I was running on an older Magisk, had to update first. Using the latest version, I can confirm it works - passes both BASIC and DEVICE checks.

For anyone on same issue, in my case for Authy: refuses to work due to not meeting minimum integrity check, even with two passes. What you need to do is uninstall Authy, clear data + cache of Play Service as well as clear data for Play Store, fresh install Authy and voìla!
________________________________
