### ISSUE TITLE
[Feature request] Support pif.json in tricky_store as per integrity-WIZARD setup

### ISSUE THREAD

**Issue by Searinox** [daboynb/playcurlNEXT#7]
Integrity-WIZARD with Tricky Store setup supports use of pif.json(without the "custom") at the /data/adb/tricky_store/pif.json path without the need for playintegrityfix. Currently playcurlNEXT will download pif.json to /data/adb if playintegrityfix is not installed.

Please support conditional for downloading pif.json to the tricky_store folder if it's installed alongside integrity-wizard but with no playintegrityfix.

**Comment by daboynb** [comment]
Hi,
The developer of Integrity Wizard removes my module by default.
I can add support only if the developer removes the code that does this.

**Comment by Searinox** [comment]
Is it known why they do this? Is it because it interferes in some way? I ask because there's the possibility that pif.json in tricky_store folder might actually be compliant behavior that removes this need.

**Comment by daboynb** [comment]
It's a common thing to do, when you deploy something you remove everything that is not essential to avoid conflicts
