### ISSUE TITLE
About BL Lock

### ISSUE THREAD

**Issue by Aron99** [daboynb/playcurlNEXT#8]
The system shows that BL is locked, but it has been unlocked through third-party software such as Momo.
![Screenshot_2024-12-06-15-31-24-222_com android settings-edit](https://github.com/user-attachments/assets/d0fe4cb9-9d16-48e8-8950-5e239ddb9aa5)
![Screenshot_2024-12-06-15-25-37-018_io github vvb2060 mahoshojo-edit](https://github.com/user-attachments/assets/2163955b-66e7-45d8-acda-865f6c119ee9)

**Comment by daboynb** [comment]
this is an issue page about playcurlNEXT
